### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by jinder** [ubilabs/kd-tree-javascript#15]
Is it possible to publish this library to NPM?

**Comment by aemkei** [comment]
@greenSnot: Is it possible to change that back since this repo is now up to date?

**Comment by greenSnot** [comment]
@aemkei done!

**Comment by aemkei** [comment]
@greenSnot Thanks! 

But can you do it one more time? I forgot to update the package.json. See https://github.com/ubilabs/kd-tree-javascript/commit/165adc0b87968df14edb0f6418bb6565ba18aeb0

**Comment by greenSnot** [comment]
@aemkei Done and what's your npm account? I would like to transfer its ownership to you.

**Comment by aemkei** [comment]
Thanks! It is aemkei, see https://www.npmjs.com/~aemkei

**Comment by patricknelson** [comment]
🎉

**Comment by patricknelson** [comment]
p.s. Thanks @aemkei for this awesome implementation. I'm searching point clouds in excess of 50k points at blazing speeds.
