### ISSUE TITLE
Add TS Support

### ISSUE THREAD

**Issue by elmarti** [ubilabs/kd-tree-javascript#24]
Adding TS Typing adds many benefits such as improved IDE intellisense and general TS functionality

**Proposed approach**

- Migrate the current project to use a basic implementation of TypeScript
- Remove UMD, add UMD as a TS build target. 
- Use TS/ES6 class for the kdTree class
- Use a class-level generic type to specify the return type for method calls. - this should not affect JS execution, but will provide a useful failure to typescript users. 

I will PR for this, but I may publish an NPM package if I don't hear back within a month.

**Comment by elmarti** [comment]
After some initial digging, it seems like there are 2 paths:

- Migrate entire project to use TS (vast re-write)
- Add TS support comments https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html

**Comment by CooperBills** [comment]
I wrote typings around the basic functionality of kd-tree-javascript, and opened a PR to get them added to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41653 - once that merges and gets published, the types should be available via npm by adding `@types/kd-tree-javascript`.

**Comment by CooperBills** [comment]
Well, that was fast! Typings have been published to `@types/kd-tree-javascript` - I've tested it in my project and it works.

**Comment by elmarti** [comment]
Thanks for this!
